name: find_flush
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-97.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_polywidget: ^1.0.1
  dio: ^5.4.2+1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icon.png"

flutter:
  assets:
  - assets/BlueprintMaps/2540CLIF/
  - assets/BlueprintMaps/60WCHARL/
  - assets/BlueprintMaps/A&S/ARTSCI/
  - assets/BlueprintMaps/A&S/CLIFTCT/
  - assets/BlueprintMaps/A&S/GEOPHYS/
  - assets/BlueprintMaps/ARMORY/
  - assets/BlueprintMaps/BRAUNSTN/
  - assets/BlueprintMaps/CCM/CCPA/
  - assets/BlueprintMaps/CCM/DIETERLE/
  - assets/BlueprintMaps/CCM/EMERY/
  - assets/BlueprintMaps/CCM/MEMORIAL/
  - assets/BlueprintMaps/CEAS/BALDWIN/
  - assets/BlueprintMaps/CEAS/MANTEI/
  - assets/BlueprintMaps/CEAS/RHODES/
  - assets/BlueprintMaps/CEAS/SWIFT/
  - assets/BlueprintMaps/CECH/DYER/
  - assets/BlueprintMaps/CECH/TEACHERS/
  - assets/BlueprintMaps/COLLAW/
  - assets/BlueprintMaps/COMMONSN-S/COMMONSN/
  - assets/BlueprintMaps/COMMONSN-S/COMMONSS/
  - assets/BlueprintMaps/CROSLEY/
  - assets/BlueprintMaps/DAAP/
  - assets/BlueprintMaps/DAAP/ALMS/
  - assets/BlueprintMaps/DAAP/ARONOFF/
  - assets/BlueprintMaps/DAAP/DAAPSTAN/
  - assets/BlueprintMaps/DAAP/WOLFSON/
  - assets/BlueprintMaps/EDWARDS/
  - assets/BlueprintMaps/FRENCH-W_/
  - assets/BlueprintMaps/Garages/CALHONGR/
  - assets/BlueprintMaps/Garages/CAMPUSGR/
  - assets/BlueprintMaps/Garages/CCMGR/
  - assets/BlueprintMaps/Garages/CLIFCTGR/
  - assets/BlueprintMaps/Garages/CORRYGR/
  - assets/BlueprintMaps/Garages/SHPRKGR/
  - assets/BlueprintMaps/Garages/UNIAVEGR/
  - assets/BlueprintMaps/Garages/VARVILGR/
  - assets/BlueprintMaps/Garages/WOODSDGR/
  - assets/BlueprintMaps/LINDHALL/
  - assets/BlueprintMaps/LNDNRCTR/
  - assets/BlueprintMaps/Libraries/BLEGEN/
  - assets/BlueprintMaps/Libraries/LANGSAM/
  - assets/BlueprintMaps/Libraries/VANWORMR/
  - assets/BlueprintMaps/MARKETPT/
  - assets/BlueprintMaps/MRICENTR/
  - assets/BlueprintMaps/MSPENCER/
  - assets/BlueprintMaps/NIPPERT/
  - assets/BlueprintMaps/PROBASCO/
  - assets/BlueprintMaps/RECCENTR/
  - assets/BlueprintMaps/RIEVSCHL/
  - assets/BlueprintMaps/Residence_Halls/CALHOUN/
  - assets/BlueprintMaps/Residence_Halls/DABNEY/
  - assets/BlueprintMaps/Residence_Halls/DANIELS/
  - assets/BlueprintMaps/Residence_Halls/MORGENS/
  - assets/BlueprintMaps/Residence_Halls/SCHNEIDR/
  - assets/BlueprintMaps/Residence_Halls/SCIOTO/
  - assets/BlueprintMaps/Residence_Halls/TURNER/
  - assets/BlueprintMaps/SHOE/
  - assets/BlueprintMaps/STEGER/
  - assets/BlueprintMaps/TUC/
  - assets/BlueprintMaps/UNIVPAV/
  - assets/BlueprintMaps/VVB/
  - assets/BlueprintMaps/ZIMMER/
  - assets/Blueprints/2540CLIF/
  - assets/Blueprints/60WCHARL/
  - assets/Blueprints/A&S/ARTSCI/
  - assets/Blueprints/A&S/CLIFTCT/
  - assets/Blueprints/A&S/GEOPHYS/
  - assets/Blueprints/ARMORY/
  - assets/Blueprints/BRAUNSTN/
  - assets/Blueprints/CCM/CCPA/
  - assets/Blueprints/CCM/DIETERLE/
  - assets/Blueprints/CCM/EMERY/
  - assets/Blueprints/CCM/MEMORIAL/
  - assets/Blueprints/CEAS/BALDWIN/
  - assets/Blueprints/CEAS/MANTEI/
  - assets/Blueprints/CEAS/RHODES/
  - assets/Blueprints/CEAS/SWIFT/
  - assets/Blueprints/CECH/DYER/
  - assets/Blueprints/CECH/TEACHERS/
  - assets/Blueprints/COLLAW/
  - assets/Blueprints/COMMONSN-S/COMMONSN/
  - assets/Blueprints/COMMONSN-S/COMMONSS/
  - assets/Blueprints/CROSLEY/
  - assets/Blueprints/DAAP/
  - assets/Blueprints/DAAP/ALMS/
  - assets/Blueprints/DAAP/ARONOFF/
  - assets/Blueprints/DAAP/DAAPSTAN/
  - assets/Blueprints/DAAP/WOLFSON/
  - assets/Blueprints/EDWARDS/
  - assets/Blueprints/FRENCH-W_/
  - assets/Blueprints/Garages/CALHONGR/
  - assets/Blueprints/Garages/CAMPUSGR/
  - assets/Blueprints/Garages/CCMGR/
  - assets/Blueprints/Garages/CLIFCTGR/
  - assets/Blueprints/Garages/CORRYGR/
  - assets/Blueprints/Garages/SHPRKGR/
  - assets/Blueprints/Garages/UNIAVEGR/
  - assets/Blueprints/Garages/VARVILGR/
  - assets/Blueprints/Garages/WOODSDGR/
  - assets/Blueprints/LINDHALL/
  - assets/Blueprints/LNDNRCTR/
  - assets/Blueprints/Libraries/BLEGEN/
  - assets/Blueprints/Libraries/LANGSAM/
  - assets/Blueprints/Libraries/VANWORMR/
  - assets/Blueprints/MARKETPT/
  - assets/Blueprints/MRICENTR/
  - assets/Blueprints/MSPENCER/
  - assets/Blueprints/NIPPERT/
  - assets/Blueprints/PROBASCO/
  - assets/Blueprints/RECCENTR/
  - assets/Blueprints/RIEVSCHL/
  - assets/Blueprints/Residence_Halls/CALHOUN/
  - assets/Blueprints/Residence_Halls/DABNEY/
  - assets/Blueprints/Residence_Halls/DANIELS/
  - assets/Blueprints/Residence_Halls/MORGENS/
  - assets/Blueprints/Residence_Halls/SCHNEIDR/
  - assets/Blueprints/Residence_Halls/SCIOTO/
  - assets/Blueprints/Residence_Halls/TURNER/
  - assets/Blueprints/SHOE/
  - assets/Blueprints/STEGER/
  - assets/Blueprints/TUC/
  - assets/Blueprints/UNIVPAV/
  - assets/Blueprints/VVB/
  - assets/Blueprints/ZIMMER/
  - assets/RoomData/2540CLIF/
  - assets/RoomData/60WCHARL/
  - assets/RoomData/A&S/ARTSCI/
  - assets/RoomData/A&S/CLIFTCT/
  - assets/RoomData/A&S/GEOPHYS/
  - assets/RoomData/ARMORY/
  - assets/RoomData/BRAUNSTN/
  - assets/RoomData/CCM/CCPA/
  - assets/RoomData/CCM/DIETERLE/
  - assets/RoomData/CCM/EMERY/
  - assets/RoomData/CCM/MEMORIAL/
  - assets/RoomData/CEAS/BALDWIN/
  - assets/RoomData/CEAS/MANTEI/
  - assets/RoomData/CEAS/RHODES/
  - assets/RoomData/CEAS/SWIFT/
  - assets/RoomData/CECH/DYER/
  - assets/RoomData/CECH/TEACHERS/
  - assets/RoomData/COLLAW/
  - assets/RoomData/COMMONSN-S/COMMONSN/
  - assets/RoomData/COMMONSN-S/COMMONSS/
  - assets/RoomData/CROSLEY/
  - assets/RoomData/DAAP/
  - assets/RoomData/DAAP/ALMS/
  - assets/RoomData/DAAP/ARONOFF/
  - assets/RoomData/DAAP/DAAPSTAN/
  - assets/RoomData/DAAP/WOLFSON/
  - assets/RoomData/EDWARDS/
  - assets/RoomData/FRENCH-W_/
  - assets/RoomData/Garages/CALHONGR/
  - assets/RoomData/Garages/CAMPUSGR/
  - assets/RoomData/Garages/CCMGR/
  - assets/RoomData/Garages/CLIFCTGR/
  - assets/RoomData/Garages/CORRYGR/
  - assets/RoomData/Garages/SHPRKGR/
  - assets/RoomData/Garages/UNIAVEGR/
  - assets/RoomData/Garages/VARVILGR/
  - assets/RoomData/Garages/WOODSDGR/
  - assets/RoomData/LINDHALL/
  - assets/RoomData/LNDNRCTR/
  - assets/RoomData/Libraries/BLEGEN/
  - assets/RoomData/Libraries/LANGSAM/
  - assets/RoomData/Libraries/VANWORMR/
  - assets/RoomData/MARKETPT/
  - assets/RoomData/MRICENTR/
  - assets/RoomData/MSPENCER/
  - assets/RoomData/NIPPERT/
  - assets/RoomData/PROBASCO/
  - assets/RoomData/RECCENTR/
  - assets/RoomData/RIEVSCHL/
  - assets/RoomData/Residence_Halls/CALHOUN/
  - assets/RoomData/Residence_Halls/DABNEY/
  - assets/RoomData/Residence_Halls/DANIELS/
  - assets/RoomData/Residence_Halls/MORGENS/
  - assets/RoomData/Residence_Halls/SCHNEIDR/
  - assets/RoomData/Residence_Halls/SCIOTO/
  - assets/RoomData/Residence_Halls/TURNER/
  - assets/RoomData/SHOE/
  - assets/RoomData/STEGER/
  - assets/RoomData/TUC/
  - assets/RoomData/UNIVPAV/
  - assets/RoomData/VVB/
  - assets/RoomData/ZIMMER/


  uses-material-design: true
