name: find_flush
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-97.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
  - Blueprints/60 West Charleton/
  - Blueprints/ARMORY/
  - Blueprints/ARONOFF/
  - Blueprints/Blegen Library/
  - Blueprints/Braunstein Hall/
  - Blueprints/CALHONGR/
  - Blueprints/CCM/
  - Blueprints/CLIFTCT/
  - Blueprints/College of Law/
  - Blueprints/COMMONSN-S/
  - Blueprints/Crosley Tower/
  - Blueprints/DAAP/
  - Blueprints/Dieterle Vocal Arts Center/
  - Blueprints/Edwards Center/
  - Blueprints/Fifth Third Arena/
  - Blueprints/French Hall/
  - Blueprints/Geology Physics Building/
  - Blueprints/LANGSAM/
  - Blueprints/Lindner Hall/
  - Blueprints/LNDNRCTR/
  - Blueprints/Mantei Center/
  - Blueprints/Marketpointe/
  - Blueprints/McMicken Hall/
  - Blueprints/MSPENCER/
  - Blueprints/NIPPERT/
  - Blueprints/RECCENTR/
  - Blueprints/Rhodes Hall/
  - Blueprints/Rieveschl Hall/
  - Blueprints/STEGER/
  - Blueprints/Swift Hall/
  - Blueprints/Taft Hall/
  - Blueprints/TEACHERS/
  - Blueprints/TUC/
  - Blueprints/UNIVPAV/
  - Blueprints/Van Wormer Hall/
  - Blueprints/VVB/
  - Blueprints/WOLFSON/
  - Blueprints/ZIMMER/

  uses-material-design: true
