name: UCMaps
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-97.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_polywidget: ^1.0.1
  dio: ^5.4.2+1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  image: ^4.1.3
  http: ^1.1.0
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "icon.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "icon.png"

flutter:
  assets:
  - assets/Blueprints/2540CLIF/
  - assets/Blueprints/60WCHARL/
  - assets/Blueprints/A&S/ARTSCI/
  - assets/Blueprints/A&S/CLIFTCT/
  - assets/Blueprints/A&S/GEOPHYS/
  - assets/Blueprints/ARMORY/
  - assets/Blueprints/BRAUNSTN/
  - assets/Blueprints/CCM/CCPA/
  - assets/Blueprints/CCM/DIETERLE/
  - assets/Blueprints/CCM/EMERY/
  - assets/Blueprints/CCM/MEMORIAL/
  - assets/Blueprints/CEAS/BALDWIN/
  - assets/Blueprints/CEAS/MANTEI/
  - assets/Blueprints/CEAS/RHODES/
  - assets/Blueprints/CEAS/SWIFT/
  - assets/Blueprints/CECH/DYER/
  - assets/Blueprints/CECH/TEACHERS/
  - assets/Blueprints/COLLAW/
  - assets/Blueprints/COMMONSN-S/COMMONSN/
  - assets/Blueprints/COMMONSN-S/COMMONSS/
  - assets/Blueprints/CROSLEY/
  - assets/Blueprints/DAAP/
  - assets/Blueprints/DAAP/ALMS/
  - assets/Blueprints/DAAP/ARONOFF/
  - assets/Blueprints/DAAP/DAAPSTAN/
  - assets/Blueprints/DAAP/WOLFSON/
  - assets/Blueprints/EDWARDS/
  - assets/Blueprints/FRENCH-W_/
  - assets/Blueprints/Garages/CALHONGR/
  - assets/Blueprints/Garages/CAMPUSGR/
  - assets/Blueprints/Garages/CCMGR/
  - assets/Blueprints/Garages/CLIFCTGR/
  - assets/Blueprints/Garages/CORRYGR/
  - assets/Blueprints/Garages/SHPRKGR/
  - assets/Blueprints/Garages/UNIAVEGR/
  - assets/Blueprints/Garages/VARVILGR/
  - assets/Blueprints/Garages/WOODSDGR/
  - assets/Blueprints/LINDHALL/
  - assets/Blueprints/LNDNRCTR/
  - assets/Blueprints/Libraries/BLEGEN/
  - assets/Blueprints/Libraries/LANGSAM/
  - assets/Blueprints/Libraries/VANWORMR/
  - assets/Blueprints/MARKETPT/
  - assets/Blueprints/MRICENTR/
  - assets/Blueprints/MSPENCER/
  - assets/Blueprints/NIPPERT/
  - assets/Blueprints/PROBASCO/
  - assets/Blueprints/RECCENTR/
  - assets/Blueprints/RIEVSCHL/
  - assets/Blueprints/Residence_Halls/CALHOUN/
  - assets/Blueprints/Residence_Halls/DABNEY/
  - assets/Blueprints/Residence_Halls/DANIELS/
  - assets/Blueprints/Residence_Halls/MORGENS/
  - assets/Blueprints/Residence_Halls/SCHNEIDR/
  - assets/Blueprints/Residence_Halls/SCIOTO/
  - assets/Blueprints/Residence_Halls/TURNER/
  - assets/Blueprints/SHOE/
  - assets/Blueprints/STEGER/
  - assets/Blueprints/TUC/
  - assets/Blueprints/UNIVPAV/
  - assets/Blueprints/VVB/
  - assets/Blueprints/ZIMMER/
  - assets/GeoMaps/2540CLIF/
  - assets/GeoMaps/60WCHARL/
  - assets/GeoMaps/A&S/ARTSCI/
  - assets/GeoMaps/A&S/CLIFTCT/
  - assets/GeoMaps/A&S/GEOPHYS/
  - assets/GeoMaps/ARMORY/
  - assets/GeoMaps/BRAUNSTN/
  - assets/GeoMaps/CCM/CCPA/
  - assets/GeoMaps/CCM/DIETERLE/
  - assets/GeoMaps/CCM/EMERY/
  - assets/GeoMaps/CCM/MEMORIAL/
  - assets/GeoMaps/CEAS/BALDWIN/
  - assets/GeoMaps/CEAS/MANTEI/
  - assets/GeoMaps/CEAS/RHODES/
  - assets/GeoMaps/CEAS/SWIFT/
  - assets/GeoMaps/CECH/DYER/
  - assets/GeoMaps/CECH/TEACHERS/
  - assets/GeoMaps/COLLAW/
  - assets/GeoMaps/COMMONSN-S/COMMONSN/
  - assets/GeoMaps/COMMONSN-S/COMMONSS/
  - assets/GeoMaps/CROSLEY/
  - assets/GeoMaps/DAAP/
  - assets/GeoMaps/DAAP/ALMS/
  - assets/GeoMaps/DAAP/ARONOFF/
  - assets/GeoMaps/DAAP/WOLFSON/
  - assets/GeoMaps/EDWARDS/
  - assets/GeoMaps/FRENCH-W_/
  - assets/GeoMaps/Garages/CALHONGR/
  - assets/GeoMaps/Garages/CAMPUSGR/
  - assets/GeoMaps/Garages/CORRYGR/
  - assets/GeoMaps/Garages/UNIAVEGR/
  - assets/GeoMaps/Garages/VARVILGR/
  - assets/GeoMaps/Garages/WOODSDGR/
  - assets/GeoMaps/LINDHALL/
  - assets/GeoMaps/LNDNRCTR/
  - assets/GeoMaps/Libraries/BLEGEN/
  - assets/GeoMaps/Libraries/LANGSAM/
  - assets/GeoMaps/Libraries/VANWORMR/
  - assets/GeoMaps/MARKETPT/
  - assets/GeoMaps/MRICENTR/
  - assets/GeoMaps/MSPENCER/
  - assets/GeoMaps/NIPPERT/
  - assets/GeoMaps/RECCENTR/
  - assets/GeoMaps/RIEVSCHL/
  - assets/GeoMaps/Residence_Halls/CALHOUN/
  - assets/GeoMaps/Residence_Halls/DABNEY/
  - assets/GeoMaps/Residence_Halls/DANIELS/
  - assets/GeoMaps/Residence_Halls/MORGENS/
  - assets/GeoMaps/Residence_Halls/SCHNEIDR/
  - assets/GeoMaps/Residence_Halls/SCIOTO/
  - assets/GeoMaps/Residence_Halls/TURNER/
  - assets/GeoMaps/SHOE/
  - assets/GeoMaps/STEGER/
  - assets/GeoMaps/TUC/
  - assets/GeoMaps/UNIVPAV/
  - assets/GeoMaps/VVB/
  - assets/GeoMaps/ZIMMER/

  uses-material-design: true
