Map<String, List<String>> buildingGeoPaths = {
'Taft Hall': [
'assets/GeoMaps/2540CLIF/2540CLIF-01.json',
'assets/GeoMaps/2540CLIF/2540CLIF-02.json',
'assets/GeoMaps/2540CLIF/2540CLIF-03.json',
'assets/GeoMaps/2540CLIF/2540CLIF-04.json',
],
'60 West Charleston': [
'assets/GeoMaps/60WCHARL/60WCHARL-01.json',
'assets/GeoMaps/60WCHARL/60WCHARL-02.json',
'assets/GeoMaps/60WCHARL/60WCHARL-B.json',
],
'A&S Hall': [
'assets/GeoMaps/A&S/ARTSCI/ARTSCI-00.json',
'assets/GeoMaps/A&S/ARTSCI/ARTSCI-01.json',
'assets/GeoMaps/A&S/ARTSCI/ARTSCI-02.json',
'assets/GeoMaps/A&S/ARTSCI/ARTSCI-03.json',
],
'Clifton Court Hall': [
'assets/GeoMaps/A&S/CLIFTCT/CLIFTCT-01.json',
'assets/GeoMaps/A&S/CLIFTCT/CLIFTCT-02.json',
'assets/GeoMaps/A&S/CLIFTCT/CLIFTCT-03.json',
'assets/GeoMaps/A&S/CLIFTCT/CLIFTCT-04.json',
'assets/GeoMaps/A&S/CLIFTCT/CLIFTCT-05.json',
],
'Geology Physics Building': [
'assets/GeoMaps/A&S/GEOPHYS/GEOPHYS-01.json',
'assets/GeoMaps/A&S/GEOPHYS/GEOPHYS-02.json',
'assets/GeoMaps/A&S/GEOPHYS/GEOPHYS-03.json',
'assets/GeoMaps/A&S/GEOPHYS/GEOPHYS-04.json',
'assets/GeoMaps/A&S/GEOPHYS/GEOPHYS-05.json',
'assets/GeoMaps/A&S/GEOPHYS/GEOPHYS-06.json',
],
'Armory Fieldhouse': [
'assets/GeoMaps/ARMORY/ARMORY-01.json',
'assets/GeoMaps/ARMORY/ARMORY-02.json',
],
'Braunstein Hall': [
'assets/GeoMaps/BRAUNSTN/BRAUNSTN-01.json',
'assets/GeoMaps/BRAUNSTN/BRAUNSTN-02.json',
'assets/GeoMaps/BRAUNSTN/BRAUNSTN-03.json',
'assets/GeoMaps/BRAUNSTN/BRAUNSTN-04.json',
],
'Corbett Center': [
'assets/GeoMaps/CCM/CCPA/CCPA-01.json',
'assets/GeoMaps/CCM/CCPA/CCPA-02.json',
'assets/GeoMaps/CCM/CCPA/CCPA-03.json',
'assets/GeoMaps/CCM/CCPA/CCPA-04.json',
],
'Dieterle Center': [
'assets/GeoMaps/CCM/DIETERLE/DIETERLE-01.json',
'assets/GeoMaps/CCM/DIETERLE/DIETERLE-02.json',
'assets/GeoMaps/CCM/DIETERLE/DIETERLE-03.json',
'assets/GeoMaps/CCM/DIETERLE/DIETERLE-04.json',
],
'Mary Emery Hall': [
'assets/GeoMaps/CCM/EMERY/EMERY-02.json',
'assets/GeoMaps/CCM/EMERY/EMERY-03.json',
'assets/GeoMaps/CCM/EMERY/EMERY-04.json',
'assets/GeoMaps/CCM/EMERY/EMERY-05.json',
],
'Memorial Hall': [
'assets/GeoMaps/CCM/MEMORIAL/MEMORIAL-01.json',
'assets/GeoMaps/CCM/MEMORIAL/MEMORIAL-02.json',
'assets/GeoMaps/CCM/MEMORIAL/MEMORIAL-03.json',
'assets/GeoMaps/CCM/MEMORIAL/MEMORIAL-04.json',
'assets/GeoMaps/CCM/MEMORIAL/MEMORIAL-05.json',
],
'Baldwin Hall': [
'assets/GeoMaps/CEAS/BALDWIN/BALDWIN-04.json',
'assets/GeoMaps/CEAS/BALDWIN/BALDWIN-05.json',
'assets/GeoMaps/CEAS/BALDWIN/BALDWIN-06.json',
'assets/GeoMaps/CEAS/BALDWIN/BALDWIN-07.json',
'assets/GeoMaps/CEAS/BALDWIN/BALDWIN-08.json',
'assets/GeoMaps/CEAS/BALDWIN/BALDWIN-09.json',
],
'Mantei Center': [
'assets/GeoMaps/CEAS/MANTEI/MANTEI-03.json',
'assets/GeoMaps/CEAS/MANTEI/MANTEI-04.json',
'assets/GeoMaps/CEAS/MANTEI/MANTEI-05.json',
'assets/GeoMaps/CEAS/MANTEI/MANTEI-06.json',
'assets/GeoMaps/CEAS/MANTEI/MANTEI-07.json',
'assets/GeoMaps/CEAS/MANTEI/MANTEI-08.json',
],
'Rhodes Hall': [
'assets/GeoMaps/CEAS/RHODES/RHODES-03.json',
'assets/GeoMaps/CEAS/RHODES/RHODES-04.json',
'assets/GeoMaps/CEAS/RHODES/RHODES-05.json',
'assets/GeoMaps/CEAS/RHODES/RHODES-06.json',
'assets/GeoMaps/CEAS/RHODES/RHODES-07.json',
'assets/GeoMaps/CEAS/RHODES/RHODES-08.json',
'assets/GeoMaps/CEAS/RHODES/RHODES-09.json',
],
'Swift Hall': [
'assets/GeoMaps/CEAS/SWIFT/SWIFT-05.json',
'assets/GeoMaps/CEAS/SWIFT/SWIFT-06.json',
'assets/GeoMaps/CEAS/SWIFT/SWIFT-07.json',
'assets/GeoMaps/CEAS/SWIFT/SWIFT-08.json',
],
'Dyer Hall': [
'assets/GeoMaps/CECH/DYER/DYER-01.json',
'assets/GeoMaps/CECH/DYER/DYER-02.json',
'assets/GeoMaps/CECH/DYER/DYER-03.json',
'assets/GeoMaps/CECH/DYER/DYER-04.json',
'assets/GeoMaps/CECH/DYER/DYER-05.json',
'assets/GeoMaps/CECH/DYER/DYER-06.json',
],
'Teachers Hall': [
'assets/GeoMaps/CECH/TEACHERS/TEACHERS-01.json',
'assets/GeoMaps/CECH/TEACHERS/TEACHERS-02.json',
'assets/GeoMaps/CECH/TEACHERS/TEACHERS-03.json',
'assets/GeoMaps/CECH/TEACHERS/TEACHERS-04.json',
'assets/GeoMaps/CECH/TEACHERS/TEACHERS-05.json',
'assets/GeoMaps/CECH/TEACHERS/TEACHERS-06.json',
],
'College of Law Building': [
'assets/GeoMaps/COLLAW/COLLAW-01.json',
'assets/GeoMaps/COLLAW/COLLAW-02.json',
'assets/GeoMaps/COLLAW/COLLAW-03.json',
'assets/GeoMaps/COLLAW/COLLAW-04.json',
'assets/GeoMaps/COLLAW/COLLAW-05.json',
'assets/GeoMaps/COLLAW/COLLAW-06.json',
'assets/GeoMaps/COLLAW/COLLAW-B.json',
],
'North Commons': [
'assets/GeoMaps/COMMONSN-S/COMMONSN/COMMONSN-01.json',
],
'South Commons': [
'assets/GeoMaps/COMMONSN-S/COMMONSS/COMMONSS-01.json',
],
'Crosley Tower': [
'assets/GeoMaps/CROSLEY/CROSLEY-01.json',
'assets/GeoMaps/CROSLEY/CROSLEY-02.json',
'assets/GeoMaps/CROSLEY/CROSLEY-03.json',
'assets/GeoMaps/CROSLEY/CROSLEY-04.json',
'assets/GeoMaps/CROSLEY/CROSLEY-05.json',
'assets/GeoMaps/CROSLEY/CROSLEY-06.json',
'assets/GeoMaps/CROSLEY/CROSLEY-07.json',
'assets/GeoMaps/CROSLEY/CROSLEY-08.json',
'assets/GeoMaps/CROSLEY/CROSLEY-09.json',
'assets/GeoMaps/CROSLEY/CROSLEY-10.json',
'assets/GeoMaps/CROSLEY/CROSLEY-11.json',
'assets/GeoMaps/CROSLEY/CROSLEY-12.json',
'assets/GeoMaps/CROSLEY/CROSLEY-13.json',
'assets/GeoMaps/CROSLEY/CROSLEY-14.json',
'assets/GeoMaps/CROSLEY/CROSLEY-15.json',
'assets/GeoMaps/CROSLEY/CROSLEY-16.json',
],
'DAAP': [
'assets/GeoMaps/DAAP/ARONOFF/ARONOFF-03.json',
'assets/GeoMaps/DAAP/ARONOFF/ARONOFF-04.json',
'assets/GeoMaps/DAAP/ARONOFF/ARONOFF-05.json',
'assets/GeoMaps/DAAP/ARONOFF/ARONOFF-06.json',
'assets/GeoMaps/DAAP/DAAP-05.json',
'assets/GeoMaps/DAAP/DAAP-06.json',
'assets/GeoMaps/DAAP/DAAP-07.json',
'assets/GeoMaps/DAAP/DAAP-08.json',
],
'Alms Building': [
'assets/GeoMaps/DAAP/ALMS/ALMS-05.json',
'assets/GeoMaps/DAAP/ALMS/ALMS-06.json',
'assets/GeoMaps/DAAP/ALMS/ALMS-07.json',
'assets/GeoMaps/DAAP/ALMS/ALMS-08.json',
],
'DAAPSTAN': [
'assets/GeoMaps/DAAP/DAAPSTAN/DAAPSTAN-01.json',
],
'Wolfsen Center': [
'assets/GeoMaps/DAAP/WOLFSON/WOLFSON-03.json',
'assets/GeoMaps/DAAP/WOLFSON/WOLFSON-04.json',
'assets/GeoMaps/DAAP/WOLFSON/WOLFSON-05.json',
'assets/GeoMaps/DAAP/WOLFSON/WOLFSON-06.json',
],
'Edwards Center': [
'assets/GeoMaps/EDWARDS/EDWARDS-01.json',
'assets/GeoMaps/EDWARDS/EDWARDS-02.json',
'assets/GeoMaps/EDWARDS/EDWARDS-03.json',
'assets/GeoMaps/EDWARDS/EDWARDS-04.json',
'assets/GeoMaps/EDWARDS/EDWARDS-05.json',
'assets/GeoMaps/EDWARDS/EDWARDS-06.json',
'assets/GeoMaps/EDWARDS/EDWARDS-07.json',
],
'French Hall': [
'assets/GeoMaps/FRENCH-W_/FRENCH-W-01.json',
'assets/GeoMaps/FRENCH-W_/FRENCH-W-02.json',
'assets/GeoMaps/FRENCH-W_/FRENCH-W-03.json',
'assets/GeoMaps/FRENCH-W_/FRENCH-W-04.json',
'assets/GeoMaps/FRENCH-W_/FRENCH-W-05.json',
'assets/GeoMaps/FRENCH-W_/FRENCH-W-06.json',
],
'Calhoun Garage': [
'assets/GeoMaps/Garages/CALHONGR/CALHONGR-P1.json',
'assets/GeoMaps/Garages/CALHONGR/CALHONGR-P2.json',
'assets/GeoMaps/Garages/CALHONGR/CALHONGR-P3.json',
'assets/GeoMaps/Garages/CALHONGR/CALHONGR-P4.json',
],
'Campus Green Garage': [
'assets/GeoMaps/Garages/CAMPUSGR/CAMPUSGR-01.json',
'assets/GeoMaps/Garages/CAMPUSGR/CAMPUSGR-02.json',
'assets/GeoMaps/Garages/CAMPUSGR/CAMPUSGR-03.json',
'assets/GeoMaps/Garages/CAMPUSGR/CAMPUSGR-04.json',
'assets/GeoMaps/Garages/CAMPUSGR/CAMPUSGR-05.json',
'assets/GeoMaps/Garages/CAMPUSGR/CAMPUSGR-06.json',
'assets/GeoMaps/Garages/CAMPUSGR/CAMPUSGR-07.json',
],
'CCMGR': [
'assets/GeoMaps/Garages/CCMGR/CCMGR-00.json',
'assets/GeoMaps/Garages/CCMGR/CCMGR-01.json',
'assets/GeoMaps/Garages/CCMGR/CCMGR-01M.json',
'assets/GeoMaps/Garages/CCMGR/CCMGR-02.json',
],
'CLIFCTGR': [
'assets/GeoMaps/Garages/CLIFCTGR/CLIFCTGR-01.json',
'assets/GeoMaps/Garages/CLIFCTGR/CLIFCTGR-02.json',
'assets/GeoMaps/Garages/CLIFCTGR/CLIFCTGR-03.json',
'assets/GeoMaps/Garages/CLIFCTGR/CLIFCTGR-04.json',
],
'Corry Garage': [
'assets/GeoMaps/Garages/CORRYGR/CORRYGR-01.json',
'assets/GeoMaps/Garages/CORRYGR/CORRYGR-02.json',
'assets/GeoMaps/Garages/CORRYGR/CORRYGR-03.json',
'assets/GeoMaps/Garages/CORRYGR/CORRYGR-04.json',
'assets/GeoMaps/Garages/CORRYGR/CORRYGR-05.json',
'assets/GeoMaps/Garages/CORRYGR/CORRYGR-06.json',
],
'SHPRKGR': [
'assets/GeoMaps/Garages/SHPRKGR/SHPRKGR-00.json',
'assets/GeoMaps/Garages/SHPRKGR/SHPRKGR-01.json',
'assets/GeoMaps/Garages/SHPRKGR/SHPRKGR-02.json',
'assets/GeoMaps/Garages/SHPRKGR/SHPRKGR-03.json',
'assets/GeoMaps/Garages/SHPRKGR/SHPRKGR-04.json',
'assets/GeoMaps/Garages/SHPRKGR/SHPRKGR-05.json',
],
'University Ave Garage': [
'assets/GeoMaps/Garages/UNIAVEGR/UNIAVEGR-01.json',
'assets/GeoMaps/Garages/UNIAVEGR/UNIAVEGR-02.json',
'assets/GeoMaps/Garages/UNIAVEGR/UNIAVEGR-03.json',
'assets/GeoMaps/Garages/UNIAVEGR/UNIAVEGR-04.json',
],
'Varsity Village Garage': [
'assets/GeoMaps/MRICENTR/MRICENTR-01.json',
'assets/GeoMaps/Garages/VARVILGR/VARVILGR-P1.json',
],
'WoodSide Garage': [
'assets/GeoMaps/Garages/WOODSDGR/WOODSDGR-01.json',
'assets/GeoMaps/Garages/WOODSDGR/WOODSDGR-02.json',
'assets/GeoMaps/Garages/WOODSDGR/WOODSDGR-03.json',
],
'Lindner Hall': [
'assets/GeoMaps/LINDHALL/LINDHALL-00.json',
'assets/GeoMaps/LINDHALL/LINDHALL-01.json',
'assets/GeoMaps/LINDHALL/LINDHALL-02.json',
'assets/GeoMaps/LINDHALL/LINDHALL-03.json',
'assets/GeoMaps/LINDHALL/LINDHALL-04.json',
],
'Lindner Athletics': [
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-01.json',
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-02.json',
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-03.json',
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-04.json',
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-05.json',
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-06.json',
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-07.json',
'assets/GeoMaps/LNDNRCTR/LNDNRCTR-08.json',
],
'Blegen Library': [
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-01.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-02.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-02M.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-03.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-03M.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-04.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-05.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-06.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-07.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-08.json',
'assets/GeoMaps/Libraries/BLEGEN/BLEGEN-09.json',
],
'Langsam Library': [
'assets/GeoMaps/Libraries/LANGSAM/LANGSAM-04.json',
'assets/GeoMaps/Libraries/LANGSAM/LANGSAM-05.json',
'assets/GeoMaps/Libraries/LANGSAM/LANGSAM-06.json',
],
'Van Wormer Hall': [
'assets/GeoMaps/Libraries/VANWORMR/VANWORMR-01.json',
'assets/GeoMaps/Libraries/VANWORMR/VANWORMR-02.json',
'assets/GeoMaps/Libraries/VANWORMR/VANWORMR-03.json',
'assets/GeoMaps/Libraries/VANWORMR/VANWORMR-04.json',
],
'Marketpointe': [
'assets/GeoMaps/MARKETPT/MARKETPT-01.json',
],
'On the Green': [
'assets/GeoMaps/MSPENCER/MSPENCER-01.json',
'assets/GeoMaps/MSPENCER/MSPENCER-02.json',
'assets/GeoMaps/MSPENCER/MSPENCER-03.json',
'assets/GeoMaps/MSPENCER/MSPENCER-04.json',
'assets/GeoMaps/MSPENCER/MSPENCER-05.json',
'assets/GeoMaps/MSPENCER/MSPENCER-06.json',
'assets/GeoMaps/MSPENCER/MSPENCER-07.json',
'assets/GeoMaps/MSPENCER/MSPENCER-08.json',
'assets/GeoMaps/MSPENCER/MSPENCER-09.json',
'assets/GeoMaps/MSPENCER/MSPENCER-G.json',
],
'Nippert Stadium': [
'assets/GeoMaps/NIPPERT/NIPPERT-01.json',
'assets/GeoMaps/NIPPERT/NIPPERT-02.json',
'assets/GeoMaps/NIPPERT/NIPPERT-03.json',
'assets/GeoMaps/NIPPERT/NIPPERT-03M.json',
'assets/GeoMaps/NIPPERT/NIPPERT-04.json',
'assets/GeoMaps/NIPPERT/NIPPERT-05.json',
],
'PROBASCO': [
'assets/GeoMaps/PROBASCO/PROBASCO-01.json',
'assets/GeoMaps/PROBASCO/PROBASCO-02.json',
'assets/GeoMaps/PROBASCO/PROBASCO-02M.json',
],
'Campus Recreation Center': [
'assets/GeoMaps/RECCENTR/RECCENTR-00.json',
'assets/GeoMaps/RECCENTR/RECCENTR-00M.json',
'assets/GeoMaps/RECCENTR/RECCENTR-01.json',
'assets/GeoMaps/RECCENTR/RECCENTR-02.json',
'assets/GeoMaps/RECCENTR/RECCENTR-03.json',
'assets/GeoMaps/RECCENTR/RECCENTR-04.json',
'assets/GeoMaps/RECCENTR/RECCENTR-05.json',
'assets/GeoMaps/RECCENTR/RECCENTR-06.json',
],
'Rieveschl Hall': [
'assets/GeoMaps/RIEVSCHL/RIEVSCHL-04.json',
'assets/GeoMaps/RIEVSCHL/RIEVSCHL-05.json',
'assets/GeoMaps/RIEVSCHL/RIEVSCHL-06.json',
'assets/GeoMaps/RIEVSCHL/RIEVSCHL-07.json',
'assets/GeoMaps/RIEVSCHL/RIEVSCHL-08.json',
'assets/GeoMaps/RIEVSCHL/RIEVSCHL-09.json',
],
'Calhoun Hall': [
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-01.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-02.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-03.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-04.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-05.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-06.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-07.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-08.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-09.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-10.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-11.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-12.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-B.json',
'assets/GeoMaps/Residence_Halls/CALHOUN/CALHOUN-G.json',
],
'Dabney Hall': [
'assets/GeoMaps/Residence_Halls/DABNEY/DABNEY-03.json',
'assets/GeoMaps/Residence_Halls/DABNEY/DABNEY-04.json',
'assets/GeoMaps/Residence_Halls/DABNEY/DABNEY-05.json',
'assets/GeoMaps/Residence_Halls/DABNEY/DABNEY-06.json',
'assets/GeoMaps/Residence_Halls/DABNEY/DABNEY-07.json',
'assets/GeoMaps/Residence_Halls/DABNEY/DABNEY-08.json',
],
'Daniels Hall': [
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-00.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-01.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-02.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-03.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-04.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-05.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-06.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-07.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-08.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-09.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-10.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-11.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-12.json',
'assets/GeoMaps/Residence_Halls/DANIELS/DANIELS-B.json',
],
'Morgens Hall': [
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-01.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-02.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-03.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-04.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-05.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-06.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-07.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-08.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-09.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-10.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-11.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-12.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-14.json',
'assets/GeoMaps/Residence_Halls/MORGENS/MORGENS-G.json',
],
'Schneider Hall': [
'assets/GeoMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-01.json',
'assets/GeoMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-02.json',
'assets/GeoMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-03.json',
'assets/GeoMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-04.json',
'assets/GeoMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-05.json',
],
'Scioto Hall': [
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-01.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-02.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-03.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-04.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-05.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-06.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-07.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-08.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-09.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-10.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-11.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-12.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-14.json',
'assets/GeoMaps/Residence_Halls/SCIOTO/SCIOTO-G.json',
],
'Turner Hall': [
'assets/GeoMaps/Residence_Halls/TURNER/TURNER-01.json',
'assets/GeoMaps/Residence_Halls/TURNER/TURNER-02.json',
'assets/GeoMaps/Residence_Halls/TURNER/TURNER-03.json',
'assets/GeoMaps/Residence_Halls/TURNER/TURNER-04.json',
'assets/GeoMaps/Residence_Halls/TURNER/TURNER-05.json',
'assets/GeoMaps/Residence_Halls/TURNER/TURNER-06.json',
'assets/GeoMaps/Residence_Halls/TURNER/TURNER-07.json',
],
'Fifth Third Arena': [
'assets/GeoMaps/SHOE/SHOE-01.json',
'assets/GeoMaps/SHOE/SHOE-02.json',
'assets/GeoMaps/SHOE/SHOE-03.json',
'assets/GeoMaps/SHOE/SHOE-04.json',
'assets/GeoMaps/SHOE/SHOE-04M.json',
'assets/GeoMaps/SHOE/SHOE-05.json',
'assets/GeoMaps/SHOE/SHOE-06.json',
],
'Steger Hall': [
'assets/GeoMaps/STEGER/STEGER-04.json',
'assets/GeoMaps/STEGER/STEGER-05.json',
'assets/GeoMaps/STEGER/STEGER-06.json',
'assets/GeoMaps/STEGER/STEGER-07.json',
'assets/GeoMaps/STEGER/STEGER-08.json',
],
'TUC': [
'assets/GeoMaps/TUC/TUC-01.json',
'assets/GeoMaps/TUC/TUC-02.json',
'assets/GeoMaps/TUC/TUC-03.json',
'assets/GeoMaps/TUC/TUC-04.json',
],
'University Pavilion': [
'assets/GeoMaps/UNIVPAV/UNIVPAV-01.json',
'assets/GeoMaps/UNIVPAV/UNIVPAV-02.json',
'assets/GeoMaps/UNIVPAV/UNIVPAV-03.json',
'assets/GeoMaps/UNIVPAV/UNIVPAV-04.json',
'assets/GeoMaps/UNIVPAV/UNIVPAV-05.json',
'assets/GeoMaps/UNIVPAV/UNIVPAV-06.json',
],
'Margo Schott Stadium': [
'assets/GeoMaps/VVB/VVB-01.json',
'assets/GeoMaps/VVB/VVB-02.json',
],
'Zimmer Hall': [
'assets/GeoMaps/ZIMMER/ZIMMER-03.json',
'assets/GeoMaps/ZIMMER/ZIMMER-04.json',
'assets/GeoMaps/ZIMMER/ZIMMER-05.json',
],
};


List<String> getbuildingGeoPathFilePaths(String directoryName) {
  return buildingGeoPaths[directoryName] ?? [];
}
