Map<String, List<String>> buildingJsonPaths = {
  'Taft Hall': [
    'BlueprintMaps/2540CLIF/2540CLIF-01.json',
    'BlueprintMaps/2540CLIF/2540CLIF-02.json',
    'BlueprintMaps/2540CLIF/2540CLIF-03.json',
    'BlueprintMaps/2540CLIF/2540CLIF-04.json',
  ],
  '60 West Charleston': [
    'BlueprintMaps/60WCHARL/60WCHARL-01.json',
    'BlueprintMaps/60WCHARL/60WCHARL-02.json',
    'BlueprintMaps/60WCHARL/60WCHARL-B.json',
  ],
  'A&S Hall': [
    'BlueprintMaps/A&S/ARTSCI/ARTSCI-00.json',
    'BlueprintMaps/A&S/ARTSCI/ARTSCI-01.json',
    'BlueprintMaps/A&S/ARTSCI/ARTSCI-02.json',
    'BlueprintMaps/A&S/ARTSCI/ARTSCI-03.json',
  ],
  'Clifton Court Hall': [
    'BlueprintMaps/A&S/CLIFTCT/CLIFTCT-01.json',
    'BlueprintMaps/A&S/CLIFTCT/CLIFTCT-02.json',
    'BlueprintMaps/A&S/CLIFTCT/CLIFTCT-03.json',
    'BlueprintMaps/A&S/CLIFTCT/CLIFTCT-04.json',
    'BlueprintMaps/A&S/CLIFTCT/CLIFTCT-05.json',
  ],
  'Geology Physics Building': [
    'BlueprintMaps/A&S/GEOPHYS/GEOPHYS-01.json',
    'BlueprintMaps/A&S/GEOPHYS/GEOPHYS-02.json',
    'BlueprintMaps/A&S/GEOPHYS/GEOPHYS-03.json',
    'BlueprintMaps/A&S/GEOPHYS/GEOPHYS-04.json',
    'BlueprintMaps/A&S/GEOPHYS/GEOPHYS-05.json',
    'BlueprintMaps/A&S/GEOPHYS/GEOPHYS-06.json',
  ],
  'Armory Fieldhouse': [
    'BlueprintMaps/ARMORY/ARMORY-01.json',
    'BlueprintMaps/ARMORY/ARMORY-02.json',
  ],
  'Braunstein Hall': [
    'BlueprintMaps/BRAUNSTN/BRAUNSTN-01.json',
    'BlueprintMaps/BRAUNSTN/BRAUNSTN-02.json',
    'BlueprintMaps/BRAUNSTN/BRAUNSTN-03.json',
    'BlueprintMaps/BRAUNSTN/BRAUNSTN-04.json',
  ],
  'Corbett Center': [
    'BlueprintMaps/CCM/CCPA/CCPA-01.json',
    'BlueprintMaps/CCM/CCPA/CCPA-02.json',
    'BlueprintMaps/CCM/CCPA/CCPA-03.json',
    'BlueprintMaps/CCM/CCPA/CCPA-04.json',
  ],
  'Dieterle Center': [
    'BlueprintMaps/CCM/DIETERLE/DIETERLE-01.json',
    'BlueprintMaps/CCM/DIETERLE/DIETERLE-02.json',
    'BlueprintMaps/CCM/DIETERLE/DIETERLE-03.json',
    'BlueprintMaps/CCM/DIETERLE/DIETERLE-04.json',
  ],
  'Mary Emery Hall': [
    'BlueprintMaps/CCM/EMERY/EMERY-02.json',
    'BlueprintMaps/CCM/EMERY/EMERY-03.json',
    'BlueprintMaps/CCM/EMERY/EMERY-04.json',
    'BlueprintMaps/CCM/EMERY/EMERY-05.json',
  ],
  'Memorial Hall': [
    'BlueprintMaps/CCM/MEMORIAL/MEMORIAL-01.json',
    'BlueprintMaps/CCM/MEMORIAL/MEMORIAL-02.json',
    'BlueprintMaps/CCM/MEMORIAL/MEMORIAL-03.json',
    'BlueprintMaps/CCM/MEMORIAL/MEMORIAL-04.json',
    'BlueprintMaps/CCM/MEMORIAL/MEMORIAL-05.json',
  ],
  'Baldwin Hall': [
    'BlueprintMaps/CEAS/BALDWIN/BALDWIN-04.json',
    'BlueprintMaps/CEAS/BALDWIN/BALDWIN-05.json',
    'BlueprintMaps/CEAS/BALDWIN/BALDWIN-06.json',
    'BlueprintMaps/CEAS/BALDWIN/BALDWIN-07.json',
    'BlueprintMaps/CEAS/BALDWIN/BALDWIN-08.json',
    'BlueprintMaps/CEAS/BALDWIN/BALDWIN-09.json',
  ],
  'Mantei Center': [
    'BlueprintMaps/CEAS/MANTEI/MANTEI-03.json',
    'BlueprintMaps/CEAS/MANTEI/MANTEI-04.json',
    'BlueprintMaps/CEAS/MANTEI/MANTEI-05.json',
    'BlueprintMaps/CEAS/MANTEI/MANTEI-06.json',
    'BlueprintMaps/CEAS/MANTEI/MANTEI-07.json',
    'BlueprintMaps/CEAS/MANTEI/MANTEI-08.json',
  ],
  'Rhodes Hall': [
    'BlueprintMaps/CEAS/RHODES/RHODES-03.json',
    'BlueprintMaps/CEAS/RHODES/RHODES-04.json',
    'BlueprintMaps/CEAS/RHODES/RHODES-05.json',
    'BlueprintMaps/CEAS/RHODES/RHODES-06.json',
    'BlueprintMaps/CEAS/RHODES/RHODES-07.json',
    'BlueprintMaps/CEAS/RHODES/RHODES-08.json',
    'BlueprintMaps/CEAS/RHODES/RHODES-09.json',
  ],
  'Swift Hall': [
    'BlueprintMaps/CEAS/SWIFT/SWIFT-05.json',
    'BlueprintMaps/CEAS/SWIFT/SWIFT-06.json',
    'BlueprintMaps/CEAS/SWIFT/SWIFT-07.json',
    'BlueprintMaps/CEAS/SWIFT/SWIFT-08.json',
  ],
  'Dyer Hall': [
    'BlueprintMaps/CECH/DYER/DYER-01.json',
    'BlueprintMaps/CECH/DYER/DYER-02.json',
    'BlueprintMaps/CECH/DYER/DYER-03.json',
    'BlueprintMaps/CECH/DYER/DYER-04.json',
    'BlueprintMaps/CECH/DYER/DYER-05.json',
    'BlueprintMaps/CECH/DYER/DYER-06.json',
  ],
  'Teachers Hall': [
    'BlueprintMaps/CECH/TEACHERS/TEACHERS-01.json',
    'BlueprintMaps/CECH/TEACHERS/TEACHERS-02.json',
    'BlueprintMaps/CECH/TEACHERS/TEACHERS-03.json',
    'BlueprintMaps/CECH/TEACHERS/TEACHERS-04.json',
    'BlueprintMaps/CECH/TEACHERS/TEACHERS-05.json',
    'BlueprintMaps/CECH/TEACHERS/TEACHERS-06.json',
  ],
  'College of Law Building': [
    'BlueprintMaps/COLLAW/COLLAW-01.json',
    'BlueprintMaps/COLLAW/COLLAW-02.json',
    'BlueprintMaps/COLLAW/COLLAW-03.json',
    'BlueprintMaps/COLLAW/COLLAW-04.json',
    'BlueprintMaps/COLLAW/COLLAW-05.json',
    'BlueprintMaps/COLLAW/COLLAW-06.json',
    'BlueprintMaps/COLLAW/COLLAW-B.json',
  ],
  'North Commons': [
    'BlueprintMaps/COMMONSN-S/COMMONSN/COMMONSN-01.json',
  ],
  'South Commons': [
    'BlueprintMaps/COMMONSN-S/COMMONSS/COMMONSS-01.json',
  ],
  'Crosley Tower': [
    'BlueprintMaps/CROSLEY/CROSLEY-01.json',
    'BlueprintMaps/CROSLEY/CROSLEY-02.json',
    'BlueprintMaps/CROSLEY/CROSLEY-03.json',
    'BlueprintMaps/CROSLEY/CROSLEY-04.json',
    'BlueprintMaps/CROSLEY/CROSLEY-05.json',
    'BlueprintMaps/CROSLEY/CROSLEY-06.json',
    'BlueprintMaps/CROSLEY/CROSLEY-07.json',
    'BlueprintMaps/CROSLEY/CROSLEY-08.json',
    'BlueprintMaps/CROSLEY/CROSLEY-09.json',
    'BlueprintMaps/CROSLEY/CROSLEY-10.json',
    'BlueprintMaps/CROSLEY/CROSLEY-11.json',
    'BlueprintMaps/CROSLEY/CROSLEY-12.json',
    'BlueprintMaps/CROSLEY/CROSLEY-13.json',
    'BlueprintMaps/CROSLEY/CROSLEY-14.json',
    'BlueprintMaps/CROSLEY/CROSLEY-15.json',
    'BlueprintMaps/CROSLEY/CROSLEY-16.json',
  ],
  'DAAP': [
    'BlueprintMaps/DAAP/ARONOFF/ARONOFF-03.json',
    'BlueprintMaps/DAAP/ARONOFF/ARONOFF-04.json',
    'BlueprintMaps/DAAP/ARONOFF/ARONOFF-05.json',
    'BlueprintMaps/DAAP/ARONOFF/ARONOFF-06.json',
    'BlueprintMaps/DAAP/DAAP-05.json',
    'BlueprintMaps/DAAP/DAAP-06.json',
    'BlueprintMaps/DAAP/DAAP-07.json',
    'BlueprintMaps/DAAP/DAAP-08.json',
  ],
  'Alms Building': [
    'BlueprintMaps/DAAP/ALMS/ALMS-05.json',
    'BlueprintMaps/DAAP/ALMS/ALMS-06.json',
    'BlueprintMaps/DAAP/ALMS/ALMS-07.json',
    'BlueprintMaps/DAAP/ALMS/ALMS-08.json',
  ],
  'DAAPSTAN': [
    'BlueprintMaps/DAAP/DAAPSTAN/DAAPSTAN-01.json',
  ],
  'Wolfsen Center': [
    'BlueprintMaps/DAAP/WOLFSON/WOLFSON-03.json',
    'BlueprintMaps/DAAP/WOLFSON/WOLFSON-04.json',
    'BlueprintMaps/DAAP/WOLFSON/WOLFSON-05.json',
    'BlueprintMaps/DAAP/WOLFSON/WOLFSON-06.json',
  ],
  'Edwards Center': [
    'BlueprintMaps/EDWARDS/EDWARDS-01.json',
    'BlueprintMaps/EDWARDS/EDWARDS-02.json',
    'BlueprintMaps/EDWARDS/EDWARDS-03.json',
    'BlueprintMaps/EDWARDS/EDWARDS-04.json',
    'BlueprintMaps/EDWARDS/EDWARDS-05.json',
    'BlueprintMaps/EDWARDS/EDWARDS-06.json',
    'BlueprintMaps/EDWARDS/EDWARDS-07.json',
  ],
  'French Hall': [
    'BlueprintMaps/FRENCH-W_/FRENCH-W-01.json',
    'BlueprintMaps/FRENCH-W_/FRENCH-W-02.json',
    'BlueprintMaps/FRENCH-W_/FRENCH-W-03.json',
    'BlueprintMaps/FRENCH-W_/FRENCH-W-04.json',
    'BlueprintMaps/FRENCH-W_/FRENCH-W-05.json',
    'BlueprintMaps/FRENCH-W_/FRENCH-W-06.json',
  ],
  'Calhoun Garage': [
    'BlueprintMaps/Garages/CALHONGR/CALHONGR-P1.json',
    'BlueprintMaps/Garages/CALHONGR/CALHONGR-P2.json',
    'BlueprintMaps/Garages/CALHONGR/CALHONGR-P3.json',
    'BlueprintMaps/Garages/CALHONGR/CALHONGR-P4.json',
  ],
  'Campus Green Garage': [
    'BlueprintMaps/Garages/CAMPUSGR/CAMPUSGR-01.json',
    'BlueprintMaps/Garages/CAMPUSGR/CAMPUSGR-02.json',
    'BlueprintMaps/Garages/CAMPUSGR/CAMPUSGR-03.json',
    'BlueprintMaps/Garages/CAMPUSGR/CAMPUSGR-04.json',
    'BlueprintMaps/Garages/CAMPUSGR/CAMPUSGR-05.json',
    'BlueprintMaps/Garages/CAMPUSGR/CAMPUSGR-06.json',
    'BlueprintMaps/Garages/CAMPUSGR/CAMPUSGR-07.json',
  ],
  'CCMGR': [
    'BlueprintMaps/Garages/CCMGR/CCMGR-00.json',
    'BlueprintMaps/Garages/CCMGR/CCMGR-01.json',
    'BlueprintMaps/Garages/CCMGR/CCMGR-01M.json',
    'BlueprintMaps/Garages/CCMGR/CCMGR-02.json',
  ],
  'CLIFCTGR': [
    'BlueprintMaps/Garages/CLIFCTGR/CLIFCTGR-01.json',
    'BlueprintMaps/Garages/CLIFCTGR/CLIFCTGR-02.json',
    'BlueprintMaps/Garages/CLIFCTGR/CLIFCTGR-03.json',
    'BlueprintMaps/Garages/CLIFCTGR/CLIFCTGR-04.json',
  ],
  'Corry Garage': [
    'BlueprintMaps/Garages/CORRYGR/CORRYGR-01.json',
    'BlueprintMaps/Garages/CORRYGR/CORRYGR-02.json',
    'BlueprintMaps/Garages/CORRYGR/CORRYGR-03.json',
    'BlueprintMaps/Garages/CORRYGR/CORRYGR-04.json',
    'BlueprintMaps/Garages/CORRYGR/CORRYGR-05.json',
    'BlueprintMaps/Garages/CORRYGR/CORRYGR-06.json',
  ],
  'SHPRKGR': [
    'BlueprintMaps/Garages/SHPRKGR/SHPRKGR-00.json',
    'BlueprintMaps/Garages/SHPRKGR/SHPRKGR-01.json',
    'BlueprintMaps/Garages/SHPRKGR/SHPRKGR-02.json',
    'BlueprintMaps/Garages/SHPRKGR/SHPRKGR-03.json',
    'BlueprintMaps/Garages/SHPRKGR/SHPRKGR-04.json',
    'BlueprintMaps/Garages/SHPRKGR/SHPRKGR-05.json',
  ],
  'University Ave Garage': [
    'BlueprintMaps/Garages/UNIAVEGR/UNIAVEGR-01.json',
    'BlueprintMaps/Garages/UNIAVEGR/UNIAVEGR-02.json',
    'BlueprintMaps/Garages/UNIAVEGR/UNIAVEGR-03.json',
    'BlueprintMaps/Garages/UNIAVEGR/UNIAVEGR-04.json',
  ],
  'Varsity Village Garage': [
    'BlueprintMaps/MRICENTR/MRICENTR-01.json',
    'BlueprintMaps/Garages/VARVILGR/VARVILGR-P1.json',
  ],
  'WoodSide Garage': [
    'BlueprintMaps/Garages/WOODSDGR/WOODSDGR-01.json',
    'BlueprintMaps/Garages/WOODSDGR/WOODSDGR-02.json',
    'BlueprintMaps/Garages/WOODSDGR/WOODSDGR-03.json',
  ],
  'Lindner Hall': [
    'BlueprintMaps/LINDHALL/LINDHALL-00.json',
    'BlueprintMaps/LINDHALL/LINDHALL-01.json',
    'BlueprintMaps/LINDHALL/LINDHALL-02.json',
    'BlueprintMaps/LINDHALL/LINDHALL-03.json',
    'BlueprintMaps/LINDHALL/LINDHALL-04.json',
  ],
  'Lindner Athletics': [
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-01.json',
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-02.json',
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-03.json',
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-04.json',
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-05.json',
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-06.json',
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-07.json',
    'BlueprintMaps/LNDNRCTR/LNDNRCTR-08.json',
  ],
  'Blegen Library': [
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-01.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-02.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-02M.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-03.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-03M.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-04.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-05.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-06.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-07.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-08.json',
    'BlueprintMaps/Libraries/BLEGEN/BLEGEN-09.json',
  ],
  'Langsam Library': [
    'BlueprintMaps/Libraries/LANGSAM/LANGSAM-04.json',
    'BlueprintMaps/Libraries/LANGSAM/LANGSAM-05.json',
    'BlueprintMaps/Libraries/LANGSAM/LANGSAM-06.json',
  ],
  'Van Wormer Hall': [
    'BlueprintMaps/Libraries/VANWORMR/VANWORMR-01.json',
    'BlueprintMaps/Libraries/VANWORMR/VANWORMR-02.json',
    'BlueprintMaps/Libraries/VANWORMR/VANWORMR-03.json',
    'BlueprintMaps/Libraries/VANWORMR/VANWORMR-04.json',
  ],
  'Marketpointe': [
    'BlueprintMaps/MARKETPT/MARKETPT-01.json',
  ],
  'MRICENTR': [

  ],
  'On the Green': [
    'BlueprintMaps/MSPENCER/MSPENCER-01.json',
    'BlueprintMaps/MSPENCER/MSPENCER-02.json',
    'BlueprintMaps/MSPENCER/MSPENCER-03.json',
    'BlueprintMaps/MSPENCER/MSPENCER-04.json',
    'BlueprintMaps/MSPENCER/MSPENCER-05.json',
    'BlueprintMaps/MSPENCER/MSPENCER-06.json',
    'BlueprintMaps/MSPENCER/MSPENCER-07.json',
    'BlueprintMaps/MSPENCER/MSPENCER-08.json',
    'BlueprintMaps/MSPENCER/MSPENCER-09.json',
    'BlueprintMaps/MSPENCER/MSPENCER-G.json',
  ],
  'Nippert Stadium': [
    'BlueprintMaps/NIPPERT/NIPPERT-01.json',
    'BlueprintMaps/NIPPERT/NIPPERT-02.json',
    'BlueprintMaps/NIPPERT/NIPPERT-03.json',
    'BlueprintMaps/NIPPERT/NIPPERT-03M.json',
    'BlueprintMaps/NIPPERT/NIPPERT-04.json',
    'BlueprintMaps/NIPPERT/NIPPERT-05.json',
  ],
  'PROBASCO': [
    'BlueprintMaps/PROBASCO/PROBASCO-01.json',
    'BlueprintMaps/PROBASCO/PROBASCO-02.json',
    'BlueprintMaps/PROBASCO/PROBASCO-02M.json',
  ],
  'Campus Recreation Center': [
    'BlueprintMaps/RECCENTR/RECCENTR-00.json',
    'BlueprintMaps/RECCENTR/RECCENTR-00M.json',
    'BlueprintMaps/RECCENTR/RECCENTR-01.json',
    'BlueprintMaps/RECCENTR/RECCENTR-02.json',
    'BlueprintMaps/RECCENTR/RECCENTR-03.json',
    'BlueprintMaps/RECCENTR/RECCENTR-04.json',
    'BlueprintMaps/RECCENTR/RECCENTR-05.json',
    'BlueprintMaps/RECCENTR/RECCENTR-06.json',
  ],
  'Rieveschl Hall': [
    'BlueprintMaps/RIEVSCHL/RIEVSCHL-04.json',
    'BlueprintMaps/RIEVSCHL/RIEVSCHL-05.json',
    'BlueprintMaps/RIEVSCHL/RIEVSCHL-06.json',
    'BlueprintMaps/RIEVSCHL/RIEVSCHL-07.json',
    'BlueprintMaps/RIEVSCHL/RIEVSCHL-08.json',
    'BlueprintMaps/RIEVSCHL/RIEVSCHL-09.json',
  ],
  'Calhoun Hall': [
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-01.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-02.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-03.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-04.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-05.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-06.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-07.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-08.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-09.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-10.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-11.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-12.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-B.json',
    'BlueprintMaps/Residence_Halls/CALHOUN/CALHOUN-G.json',
  ],
  'Dabney Hall': [
    'BlueprintMaps/Residence_Halls/DABNEY/DABNEY-03.json',
    'BlueprintMaps/Residence_Halls/DABNEY/DABNEY-04.json',
    'BlueprintMaps/Residence_Halls/DABNEY/DABNEY-05.json',
    'BlueprintMaps/Residence_Halls/DABNEY/DABNEY-06.json',
    'BlueprintMaps/Residence_Halls/DABNEY/DABNEY-07.json',
    'BlueprintMaps/Residence_Halls/DABNEY/DABNEY-08.json',
  ],
  'Daniels Hall': [
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-00.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-01.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-02.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-03.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-04.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-05.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-06.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-07.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-08.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-09.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-10.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-11.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-12.json',
    'BlueprintMaps/Residence_Halls/DANIELS/DANIELS-B.json',
  ],
  'Morgens Hall': [
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-01.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-02.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-03.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-04.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-05.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-06.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-07.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-08.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-09.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-10.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-11.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-12.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-14.json',
    'BlueprintMaps/Residence_Halls/MORGENS/MORGENS-G.json',
  ],
  'Schneider Hall': [
    'BlueprintMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-01.json',
    'BlueprintMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-02.json',
    'BlueprintMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-03.json',
    'BlueprintMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-04.json',
    'BlueprintMaps/Residence_Halls/SCHNEIDR/SCHNEIDR-05.json',
  ],
  'Scioto Hall': [
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-01.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-02.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-03.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-04.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-05.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-06.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-07.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-08.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-09.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-10.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-11.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-12.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-14.json',
    'BlueprintMaps/Residence_Halls/SCIOTO/SCIOTO-G.json',
  ],
  'Turner Hall': [
    'BlueprintMaps/Residence_Halls/TURNER/TURNER-01.json',
    'BlueprintMaps/Residence_Halls/TURNER/TURNER-02.json',
    'BlueprintMaps/Residence_Halls/TURNER/TURNER-03.json',
    'BlueprintMaps/Residence_Halls/TURNER/TURNER-04.json',
    'BlueprintMaps/Residence_Halls/TURNER/TURNER-05.json',
    'BlueprintMaps/Residence_Halls/TURNER/TURNER-06.json',
    'BlueprintMaps/Residence_Halls/TURNER/TURNER-07.json',
  ],
  'Fifth Third Arena': [
    'BlueprintMaps/SHOE/SHOE-01.json',
    'BlueprintMaps/SHOE/SHOE-02.json',
    'BlueprintMaps/SHOE/SHOE-03.json',
    'BlueprintMaps/SHOE/SHOE-04.json',
    'BlueprintMaps/SHOE/SHOE-04M.json',
    'BlueprintMaps/SHOE/SHOE-05.json',
    'BlueprintMaps/SHOE/SHOE-06.json',
  ],
  'Steger Hall': [
    'BlueprintMaps/STEGER/STEGER-04.json',
    'BlueprintMaps/STEGER/STEGER-05.json',
    'BlueprintMaps/STEGER/STEGER-06.json',
    'BlueprintMaps/STEGER/STEGER-07.json',
    'BlueprintMaps/STEGER/STEGER-08.json',
  ],
  'TUC': [
    'BlueprintMaps/TUC/TUC-01.json',
    'BlueprintMaps/TUC/TUC-02.json',
    'BlueprintMaps/TUC/TUC-03.json',
    'BlueprintMaps/TUC/TUC-04.json',
  ],
  'University Pavilion': [
    'BlueprintMaps/UNIVPAV/UNIVPAV-01.json',
    'BlueprintMaps/UNIVPAV/UNIVPAV-02.json',
    'BlueprintMaps/UNIVPAV/UNIVPAV-03.json',
    'BlueprintMaps/UNIVPAV/UNIVPAV-04.json',
    'BlueprintMaps/UNIVPAV/UNIVPAV-05.json',
    'BlueprintMaps/UNIVPAV/UNIVPAV-06.json',
  ],
  'Margo Schott Stadium': [
    'BlueprintMaps/VVB/VVB-01.json',
    'BlueprintMaps/VVB/VVB-02.json',
  ],
  'Zimmer Hall': [
    'BlueprintMaps/ZIMMER/ZIMMER-03.json',
    'BlueprintMaps/ZIMMER/ZIMMER-04.json',
    'BlueprintMaps/ZIMMER/ZIMMER-05.json',
  ],
};

List<String> getbuildingJsonPathFilePaths(String directoryName) {
  return buildingJsonPaths[directoryName] ?? [];
}
