Map<String, List<String>> buildingImagePaths = {
  'Taft Hall': [
    'Blueprints/2540CLIF/2540CLIF-01.png',
    'Blueprints/2540CLIF/2540CLIF-02.png',
    'Blueprints/2540CLIF/2540CLIF-03.png',
    'Blueprints/2540CLIF/2540CLIF-04.png',
  ],
  '60 West Charleston': [
    'Blueprints/60WCHARL/60WCHARL-01.png',
    'Blueprints/60WCHARL/60WCHARL-02.png',
    'Blueprints/60WCHARL/60WCHARL-B.png',
  ],
  'A&S Hall': [
    'Blueprints/A&S/ARTSCI/ARTSCI-00.png',
    'Blueprints/A&S/ARTSCI/ARTSCI-01.png',
    'Blueprints/A&S/ARTSCI/ARTSCI-02.png',
    'Blueprints/A&S/ARTSCI/ARTSCI-03.png',
  ],
  'Clifton Court Hall': [
    'Blueprints/A&S/CLIFTCT/CLIFTCT-01.png',
    'Blueprints/A&S/CLIFTCT/CLIFTCT-02.png',
    'Blueprints/A&S/CLIFTCT/CLIFTCT-03.png',
    'Blueprints/A&S/CLIFTCT/CLIFTCT-04.png',
    'Blueprints/A&S/CLIFTCT/CLIFTCT-05.png',
  ],
  'Geology Physics Building': [
    'Blueprints/A&S/GEOPHYS/GEOPHYS-01.png',
    'Blueprints/A&S/GEOPHYS/GEOPHYS-02.png',
    'Blueprints/A&S/GEOPHYS/GEOPHYS-03.png',
    'Blueprints/A&S/GEOPHYS/GEOPHYS-04.png',
    'Blueprints/A&S/GEOPHYS/GEOPHYS-05.png',
    'Blueprints/A&S/GEOPHYS/GEOPHYS-06.png',
  ],
  'Armory Fieldhouse': [
    'Blueprints/ARMORY/ARMORY-01.png',
    'Blueprints/ARMORY/ARMORY-02.png',
  ],
  'Braunstein Hall': [
    'Blueprints/BRAUNSTN/BRAUNSTN-01.png',
    'Blueprints/BRAUNSTN/BRAUNSTN-02.png',
    'Blueprints/BRAUNSTN/BRAUNSTN-03.png',
    'Blueprints/BRAUNSTN/BRAUNSTN-04.png',
  ],
  'Corbett Center': [
    'Blueprints/CCM/CCPA/CCPA-01.png',
    'Blueprints/CCM/CCPA/CCPA-02.png',
    'Blueprints/CCM/CCPA/CCPA-03.png',
    'Blueprints/CCM/CCPA/CCPA-04.png',
  ],
  'Dieterle Center': [
    'Blueprints/CCM/DIETERLE/DIETERLE-01.png',
    'Blueprints/CCM/DIETERLE/DIETERLE-02.png',
    'Blueprints/CCM/DIETERLE/DIETERLE-03.png',
    'Blueprints/CCM/DIETERLE/DIETERLE-04.png',
  ],
  'Mary Emery Hall': [
    'Blueprints/CCM/EMERY/EMERY-02.png',
    'Blueprints/CCM/EMERY/EMERY-03.png',
    'Blueprints/CCM/EMERY/EMERY-04.png',
    'Blueprints/CCM/EMERY/EMERY-05.png',
  ],
  'Memorial Hall': [
    'Blueprints/CCM/MEMORIAL/MEMORIAL-01.png',
    'Blueprints/CCM/MEMORIAL/MEMORIAL-02.png',
    'Blueprints/CCM/MEMORIAL/MEMORIAL-03.png',
    'Blueprints/CCM/MEMORIAL/MEMORIAL-04.png',
    'Blueprints/CCM/MEMORIAL/MEMORIAL-05.png',
  ],
  'Baldwin Hall': [
    'Blueprints/CEAS/BALDWIN/BALDWIN-04.png',
    'Blueprints/CEAS/BALDWIN/BALDWIN-05.png',
    'Blueprints/CEAS/BALDWIN/BALDWIN-06.png',
    'Blueprints/CEAS/BALDWIN/BALDWIN-07.png',
    'Blueprints/CEAS/BALDWIN/BALDWIN-08.png',
    'Blueprints/CEAS/BALDWIN/BALDWIN-09.png',
  ],
  'Mantei Center': [
    'Blueprints/CEAS/MANTEI/MANTEI-03.png',
    'Blueprints/CEAS/MANTEI/MANTEI-04.png',
    'Blueprints/CEAS/MANTEI/MANTEI-05.png',
    'Blueprints/CEAS/MANTEI/MANTEI-06.png',
    'Blueprints/CEAS/MANTEI/MANTEI-07.png',
    'Blueprints/CEAS/MANTEI/MANTEI-08.png',
  ],
  'Rhodes Hall': [
    'Blueprints/CEAS/RHODES/RHODES-03.png',
    'Blueprints/CEAS/RHODES/RHODES-04.png',
    'Blueprints/CEAS/RHODES/RHODES-05.png',
    'Blueprints/CEAS/RHODES/RHODES-06.png',
    'Blueprints/CEAS/RHODES/RHODES-07.png',
    'Blueprints/CEAS/RHODES/RHODES-08.png',
    'Blueprints/CEAS/RHODES/RHODES-09.png',
  ],
  'Swift Hall': [
    'Blueprints/CEAS/SWIFT/SWIFT-05.png',
    'Blueprints/CEAS/SWIFT/SWIFT-06.png',
    'Blueprints/CEAS/SWIFT/SWIFT-07.png',
    'Blueprints/CEAS/SWIFT/SWIFT-08.png',
  ],
  'Dyer Hall': [
    'Blueprints/CECH/DYER/DYER-01.png',
    'Blueprints/CECH/DYER/DYER-02.png',
    'Blueprints/CECH/DYER/DYER-03.png',
    'Blueprints/CECH/DYER/DYER-04.png',
    'Blueprints/CECH/DYER/DYER-05.png',
    'Blueprints/CECH/DYER/DYER-06.png',
  ],
  'Teachers Hall': [
    'Blueprints/CECH/TEACHERS/TEACHERS-01.png',
    'Blueprints/CECH/TEACHERS/TEACHERS-02.png',
    'Blueprints/CECH/TEACHERS/TEACHERS-03.png',
    'Blueprints/CECH/TEACHERS/TEACHERS-04.png',
    'Blueprints/CECH/TEACHERS/TEACHERS-05.png',
    'Blueprints/CECH/TEACHERS/TEACHERS-06.png',
  ],
  'College of Law Building': [
    'Blueprints/COLLAW/COLLAW-01.png',
    'Blueprints/COLLAW/COLLAW-02.png',
    'Blueprints/COLLAW/COLLAW-03.png',
    'Blueprints/COLLAW/COLLAW-04.png',
    'Blueprints/COLLAW/COLLAW-05.png',
    'Blueprints/COLLAW/COLLAW-06.png',
    'Blueprints/COLLAW/COLLAW-B.png',
  ],
  'North Commons': [
    'Blueprints/COMMONSN-S/COMMONSN/COMMONSN-01.png',
  ],
  'South Commons': [
    'Blueprints/COMMONSN-S/COMMONSS/COMMONSS-01.png',
  ],
  'Crosley Tower': [
    'Blueprints/CROSLEY/CROSLEY-01.png',
    'Blueprints/CROSLEY/CROSLEY-02.png',
    'Blueprints/CROSLEY/CROSLEY-03.png',
    'Blueprints/CROSLEY/CROSLEY-04.png',
    'Blueprints/CROSLEY/CROSLEY-05.png',
    'Blueprints/CROSLEY/CROSLEY-06.png',
    'Blueprints/CROSLEY/CROSLEY-07.png',
    'Blueprints/CROSLEY/CROSLEY-08.png',
    'Blueprints/CROSLEY/CROSLEY-09.png',
    'Blueprints/CROSLEY/CROSLEY-10.png',
    'Blueprints/CROSLEY/CROSLEY-11.png',
    'Blueprints/CROSLEY/CROSLEY-12.png',
    'Blueprints/CROSLEY/CROSLEY-13.png',
    'Blueprints/CROSLEY/CROSLEY-14.png',
    'Blueprints/CROSLEY/CROSLEY-15.png',
    'Blueprints/CROSLEY/CROSLEY-16.png',
  ],
  'DAAP': [
    'Blueprints/DAAP/DAAP-05.png',
    'Blueprints/DAAP/DAAP-06.png',
    'Blueprints/DAAP/DAAP-07.png',
    'Blueprints/DAAP/DAAP-08.png',
  ],
  'Alms Building': [
    'Blueprints/DAAP/ALMS/ALMS-05.png',
    'Blueprints/DAAP/ALMS/ALMS-06.png',
    'Blueprints/DAAP/ALMS/ALMS-07.png',
    'Blueprints/DAAP/ALMS/ALMS-08.png',
  ],
  'ARONOFF': [
    'Blueprints/DAAP/ARONOFF/ARONOFF-03.png',
    'Blueprints/DAAP/ARONOFF/ARONOFF-04.png',
    'Blueprints/DAAP/ARONOFF/ARONOFF-05.png',
    'Blueprints/DAAP/ARONOFF/ARONOFF-06.png',
  ],
  'DAAPSTAN': [
    'Blueprints/DAAP/DAAPSTAN/DAAPSTAN-01.png',
  ],
  'Wolfsen Center': [
    'Blueprints/DAAP/WOLFSON/WOLFSON-03.png',
    'Blueprints/DAAP/WOLFSON/WOLFSON-04.png',
    'Blueprints/DAAP/WOLFSON/WOLFSON-05.png',
    'Blueprints/DAAP/WOLFSON/WOLFSON-06.png',
  ],
  'Edwards Center': [
    'Blueprints/EDWARDS/EDWARDS-01.png',
    'Blueprints/EDWARDS/EDWARDS-02.png',
    'Blueprints/EDWARDS/EDWARDS-03.png',
    'Blueprints/EDWARDS/EDWARDS-04.png',
    'Blueprints/EDWARDS/EDWARDS-05.png',
    'Blueprints/EDWARDS/EDWARDS-06.png',
    'Blueprints/EDWARDS/EDWARDS-07.png',
  ],
  'French Hall': [
    'Blueprints/FRENCH-W_/FRENCH-W-01.png',
    'Blueprints/FRENCH-W_/FRENCH-W-02.png',
    'Blueprints/FRENCH-W_/FRENCH-W-03.png',
    'Blueprints/FRENCH-W_/FRENCH-W-04.png',
    'Blueprints/FRENCH-W_/FRENCH-W-05.png',
    'Blueprints/FRENCH-W_/FRENCH-W-06.png',
  ],
  'Calhoun Garage': [
    'Blueprints/Garages/CALHONGR/CALHONGR-P1.png',
    'Blueprints/Garages/CALHONGR/CALHONGR-P2.png',
    'Blueprints/Garages/CALHONGR/CALHONGR-P3.png',
    'Blueprints/Garages/CALHONGR/CALHONGR-P4.png',
  ],
  'Campus Green Garage': [
    'Blueprints/Garages/CAMPUSGR/CAMPUSGR-01.png',
    'Blueprints/Garages/CAMPUSGR/CAMPUSGR-02.png',
    'Blueprints/Garages/CAMPUSGR/CAMPUSGR-03.png',
    'Blueprints/Garages/CAMPUSGR/CAMPUSGR-04.png',
    'Blueprints/Garages/CAMPUSGR/CAMPUSGR-05.png',
    'Blueprints/Garages/CAMPUSGR/CAMPUSGR-06.png',
    'Blueprints/Garages/CAMPUSGR/CAMPUSGR-07.png',
  ],
  'CCMGR': [
    'Blueprints/Garages/CCMGR/CCMGR-00.png',
    'Blueprints/Garages/CCMGR/CCMGR-01.png',
    'Blueprints/Garages/CCMGR/CCMGR-01M.png',
    'Blueprints/Garages/CCMGR/CCMGR-02.png',
  ],
  'CLIFCTGR': [
    'Blueprints/Garages/CLIFCTGR/CLIFCTGR-01.png',
    'Blueprints/Garages/CLIFCTGR/CLIFCTGR-02.png',
    'Blueprints/Garages/CLIFCTGR/CLIFCTGR-03.png',
    'Blueprints/Garages/CLIFCTGR/CLIFCTGR-04.png',
  ],
  'Corry Garage': [
    'Blueprints/Garages/CORRYGR/CORRYGR-01.png',
    'Blueprints/Garages/CORRYGR/CORRYGR-02.png',
    'Blueprints/Garages/CORRYGR/CORRYGR-03.png',
    'Blueprints/Garages/CORRYGR/CORRYGR-04.png',
    'Blueprints/Garages/CORRYGR/CORRYGR-05.png',
    'Blueprints/Garages/CORRYGR/CORRYGR-06.png',
  ],
  'SHPRKGR': [
    'Blueprints/Garages/SHPRKGR/SHPRKGR-00.png',
    'Blueprints/Garages/SHPRKGR/SHPRKGR-01.png',
    'Blueprints/Garages/SHPRKGR/SHPRKGR-02.png',
    'Blueprints/Garages/SHPRKGR/SHPRKGR-03.png',
    'Blueprints/Garages/SHPRKGR/SHPRKGR-04.png',
    'Blueprints/Garages/SHPRKGR/SHPRKGR-05.png',
  ],
  'University Ave Garage': [
    'Blueprints/Garages/UNIAVEGR/UNIAVEGR-01.png',
    'Blueprints/Garages/UNIAVEGR/UNIAVEGR-02.png',
    'Blueprints/Garages/UNIAVEGR/UNIAVEGR-03.png',
    'Blueprints/Garages/UNIAVEGR/UNIAVEGR-04.png',
  ],
  'Varsity Village Garage': [
    'Blueprints/MRICENTR/MRICENTR-01.png',
    'Blueprints/Garages/VARVILGR/VARVILGR-P1.png',
  ],
  'WoodSide Garage': [
    'Blueprints/Garages/WOODSDGR/WOODSDGR-01.png',
    'Blueprints/Garages/WOODSDGR/WOODSDGR-02.png',
    'Blueprints/Garages/WOODSDGR/WOODSDGR-03.png',
  ],
  'Lindner Hall': [
    'Blueprints/LINDHALL/LINDHALL-00.png',
    'Blueprints/LINDHALL/LINDHALL-01.png',
    'Blueprints/LINDHALL/LINDHALL-02.png',
    'Blueprints/LINDHALL/LINDHALL-03.png',
    'Blueprints/LINDHALL/LINDHALL-04.png',
  ],
  'Lindner Athletics': [
    'Blueprints/LNDNRCTR/LNDNRCTR-01.png',
    'Blueprints/LNDNRCTR/LNDNRCTR-02.png',
    'Blueprints/LNDNRCTR/LNDNRCTR-03.png',
    'Blueprints/LNDNRCTR/LNDNRCTR-04.png',
    'Blueprints/LNDNRCTR/LNDNRCTR-05.png',
    'Blueprints/LNDNRCTR/LNDNRCTR-06.png',
    'Blueprints/LNDNRCTR/LNDNRCTR-07.png',
    'Blueprints/LNDNRCTR/LNDNRCTR-08.png',
  ],
  'Blegen Library': [
    'Blueprints/Libraries/BLEGEN/BLEGEN-01.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-02.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-02M.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-03.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-03M.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-04.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-05.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-06.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-07.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-08.png',
    'Blueprints/Libraries/BLEGEN/BLEGEN-09.png',
  ],
  'Langsam Library': [
    'Blueprints/Libraries/LANGSAM/LANGSAM-04.png',
    'Blueprints/Libraries/LANGSAM/LANGSAM-05.png',
    'Blueprints/Libraries/LANGSAM/LANGSAM-06.png',
  ],
  'Van Wormer Hall': [
    'Blueprints/Libraries/VANWORMR/VANWORMR-01.png',
    'Blueprints/Libraries/VANWORMR/VANWORMR-02.png',
    'Blueprints/Libraries/VANWORMR/VANWORMR-03.png',
    'Blueprints/Libraries/VANWORMR/VANWORMR-04.png',
  ],
  'Marketpointe': [
    'Blueprints/MARKETPT/MARKETPT-01.png',
  ],
  'MRICENTR': [

  ],
  'On the Green': [
    'Blueprints/MSPENCER/MSPENCER-01.png',
    'Blueprints/MSPENCER/MSPENCER-02.png',
    'Blueprints/MSPENCER/MSPENCER-03.png',
    'Blueprints/MSPENCER/MSPENCER-04.png',
    'Blueprints/MSPENCER/MSPENCER-05.png',
    'Blueprints/MSPENCER/MSPENCER-06.png',
    'Blueprints/MSPENCER/MSPENCER-07.png',
    'Blueprints/MSPENCER/MSPENCER-08.png',
    'Blueprints/MSPENCER/MSPENCER-09.png',
    'Blueprints/MSPENCER/MSPENCER-G.png',
  ],
  'Nippert Stadium': [
    'Blueprints/NIPPERT/NIPPERT-01.png',
    'Blueprints/NIPPERT/NIPPERT-02.png',
    'Blueprints/NIPPERT/NIPPERT-03.png',
    'Blueprints/NIPPERT/NIPPERT-03M.png',
    'Blueprints/NIPPERT/NIPPERT-04.png',
    'Blueprints/NIPPERT/NIPPERT-05.png',
  ],
  'PROBASCO': [
    'Blueprints/PROBASCO/PROBASCO-01.png',
    'Blueprints/PROBASCO/PROBASCO-02.png',
    'Blueprints/PROBASCO/PROBASCO-02M.png',
  ],
  'Campus Recreation Center': [
    'Blueprints/RECCENTR/RECCENTR-00.png',
    'Blueprints/RECCENTR/RECCENTR-00M.png',
    'Blueprints/RECCENTR/RECCENTR-01.png',
    'Blueprints/RECCENTR/RECCENTR-02.png',
    'Blueprints/RECCENTR/RECCENTR-03.png',
    'Blueprints/RECCENTR/RECCENTR-04.png',
    'Blueprints/RECCENTR/RECCENTR-05.png',
    'Blueprints/RECCENTR/RECCENTR-06.png',
  ],
  'Rieveschl Hall': [
    'Blueprints/RIEVSCHL/RIEVSCHL-04.png',
    'Blueprints/RIEVSCHL/RIEVSCHL-05.png',
    'Blueprints/RIEVSCHL/RIEVSCHL-06.png',
    'Blueprints/RIEVSCHL/RIEVSCHL-07.png',
    'Blueprints/RIEVSCHL/RIEVSCHL-08.png',
    'Blueprints/RIEVSCHL/RIEVSCHL-09.png',
  ],
  'Calhoun Hall': [
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-01.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-02.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-03.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-04.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-05.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-06.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-07.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-08.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-09.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-10.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-11.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-12.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-B.png',
    'Blueprints/Residence_Halls/CALHOUN/CALHOUN-G.png',
  ],
  'Dabney Hall': [
    'Blueprints/Residence_Halls/DABNEY/DABNEY-03.png',
    'Blueprints/Residence_Halls/DABNEY/DABNEY-04.png',
    'Blueprints/Residence_Halls/DABNEY/DABNEY-05.png',
    'Blueprints/Residence_Halls/DABNEY/DABNEY-06.png',
    'Blueprints/Residence_Halls/DABNEY/DABNEY-07.png',
    'Blueprints/Residence_Halls/DABNEY/DABNEY-08.png',
  ],
  'Daniels Hall': [
    'Blueprints/Residence_Halls/DANIELS/DANIELS-00.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-01.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-02.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-03.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-04.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-05.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-06.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-07.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-08.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-09.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-10.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-11.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-12.png',
    'Blueprints/Residence_Halls/DANIELS/DANIELS-B.png',
  ],
  'Morgens Hall': [
    'Blueprints/Residence_Halls/MORGENS/MORGENS-01.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-02.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-03.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-04.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-05.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-06.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-07.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-08.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-09.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-10.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-11.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-12.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-14.png',
    'Blueprints/Residence_Halls/MORGENS/MORGENS-G.png',
  ],
  'Schneider Hall': [
    'Blueprints/Residence_Halls/SCHNEIDR/SCHNEIDR-01.png',
    'Blueprints/Residence_Halls/SCHNEIDR/SCHNEIDR-02.png',
    'Blueprints/Residence_Halls/SCHNEIDR/SCHNEIDR-03.png',
    'Blueprints/Residence_Halls/SCHNEIDR/SCHNEIDR-04.png',
    'Blueprints/Residence_Halls/SCHNEIDR/SCHNEIDR-05.png',
  ],
  'Scioto Hall': [
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-01.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-02.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-03.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-04.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-05.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-06.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-07.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-08.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-09.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-10.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-11.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-12.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-14.png',
    'Blueprints/Residence_Halls/SCIOTO/SCIOTO-G.png',
  ],
  'Turner Hall': [
    'Blueprints/Residence_Halls/TURNER/TURNER-01.png',
    'Blueprints/Residence_Halls/TURNER/TURNER-02.png',
    'Blueprints/Residence_Halls/TURNER/TURNER-03.png',
    'Blueprints/Residence_Halls/TURNER/TURNER-04.png',
    'Blueprints/Residence_Halls/TURNER/TURNER-05.png',
    'Blueprints/Residence_Halls/TURNER/TURNER-06.png',
    'Blueprints/Residence_Halls/TURNER/TURNER-07.png',
  ],
  'Fifth Third Arena': [
    'Blueprints/SHOE/SHOE-01.png',
    'Blueprints/SHOE/SHOE-02.png',
    'Blueprints/SHOE/SHOE-03.png',
    'Blueprints/SHOE/SHOE-04.png',
    'Blueprints/SHOE/SHOE-04M.png',
    'Blueprints/SHOE/SHOE-05.png',
    'Blueprints/SHOE/SHOE-06.png',
  ],
  'Steger Hall': [
    'Blueprints/STEGER/STEGER-04.png',
    'Blueprints/STEGER/STEGER-05.png',
    'Blueprints/STEGER/STEGER-06.png',
    'Blueprints/STEGER/STEGER-07.png',
    'Blueprints/STEGER/STEGER-08.png',
  ],
  'TUC': [
    'Blueprints/TUC/TUC-01.png',
    'Blueprints/TUC/TUC-02.png',
    'Blueprints/TUC/TUC-03.png',
    'Blueprints/TUC/TUC-04.png',
  ],
  'University Pavilion': [
    'Blueprints/UNIVPAV/UNIVPAV-01.png',
    'Blueprints/UNIVPAV/UNIVPAV-02.png',
    'Blueprints/UNIVPAV/UNIVPAV-03.png',
    'Blueprints/UNIVPAV/UNIVPAV-04.png',
    'Blueprints/UNIVPAV/UNIVPAV-05.png',
    'Blueprints/UNIVPAV/UNIVPAV-06.png',
  ],
  'Margo Schott Stadium': [
    'Blueprints/VVB/VVB-01.png',
    'Blueprints/VVB/VVB-02.png',
  ],
  'Zimmer Hall': [
    'Blueprints/ZIMMER/ZIMMER-03.png',
    'Blueprints/ZIMMER/ZIMMER-04.png',
    'Blueprints/ZIMMER/ZIMMER-05.png',
  ],
};

List<String> getbuildingImagePathFilePaths(String directoryName) {
  return buildingImagePaths[directoryName] ?? [];
}
